### ISSUE TITLE
Can not compile app - unexplained error

### ISSUE THREAD

**Issue by Leooo** [aexmachina/ember-devtools#21]
Hello, an error appeared a few days ago which prevents me from compiling my Ember app, it must come from some place in my code but all I could do to trace it till now was to go back to ember-devtools. If I remove the addon from package.json things work properly again. Any idea what this could be? Many thanks

On Ember 1.12, last ember-devtools version:

/home/leo/rails_projects/AssessUp/frontend/node_modules/ember-devtools/index.js:6
16:14:10 web.1    |   isEnabled() {
16:14:10 web.1    |            ^
16:14:10 web.1    | Unexpected token (
16:14:10 web.1    | /home/leo/rails_projects/AssessUp/frontend/node_modules/ember-devtools/index.js:6
16:14:10 web.1    |   isEnabled() {
16:14:10 web.1    |            ^
16:14:10 web.1    | SyntaxError: Unexpected token (
16:14:10 web.1    |     at exports.runInThisContext (vm.js:73:16)
16:14:10 web.1    |     at Module._compile (module.js:443:25)
16:14:10 web.1    |     at Object.Module._extensions..js (module.js:478:10)
16:14:10 web.1    |     at Module.load (module.js:355:32)
16:14:10 web.1    |     at Function.Module._load (module.js:310:12)
16:14:10 web.1    |     at Module.require (module.js:365:17)
16:14:10 web.1    |     at require (module.js:384:17)
16:14:10 web.1    |     at Function.Addon.lookup (/home/leo/rails_projects/AssessUp/frontend/node_modules/ember-cli/lib/models/addon.js:702:19)
16:14:10 web.1    |     at /home/leo/rails_projects/AssessUp/frontend/node_modules/ember-cli/lib/models/addons-factory.js:47:36
16:14:10 web.1    |     at visit (/home/leo/rails_projects/AssessUp/frontend/node_modules/ember-cli/lib/utilities/DAG.js:23:3)

**Comment by aexmachina** [comment]
Sorry, I fixed that already but forgot to push it to npm. That's fixed now.

**Comment by Leooo** [comment]
Thanks!

**Comment by Leooo** [comment]
Actually it still does't compile with the 4.3.1 version:

undefined is not a function
11:22:23 web.1    | TypeError: undefined is not a function
11:22:23 web.1    |     at module.exports (/home/leo/rails_projects/AssessUp/frontend/node_modules/ember-devtools/config/environment.js:8:40)
11:22:23 web.1    |     at Class.Addon.config (/home/leo/rails_projects/AssessUp/frontend/node_modules/ember-cli/lib/models/addon.js:637:12)
11:22:23 web.1    |     at /home/leo/rails_projects/AssessUp/frontend/node_modules/ember-cli/lib/models/project.js:201:27
11:22:23 web.1    |     at Array.reduce (native)
11:22:23 web.1    |     at Project.getAddonsConfig (/home/leo/rails_projects/AssessUp/frontend/node_modules/ember-cli/lib/models/project.js:199:22)
11:22:23 web.1    |     at Project.config (/home/leo/rails_projects/AssessUp/frontend/node_modules/ember-cli/lib/models/project.js:177:29)
11:22:23 web.1    |     at Class.module.exports.isEnabled (/home/leo/rails_projects/AssessUp/frontend/node_modules/ember-devtools/index.js:7:40)
11:22:23 web.1    |     at EmberApp.<anonymous> (/home/leo/rails_projects/AssessUp/frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:323:35)
11:22:23 web.1    |     at Array.filter (native)
11:22:23 web.1    |     at EmberApp._notifyAddonIncluded (/home/leo/rails_projects/AssessUp/frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:320:45)

Thanks

**Comment by Leooo** [comment]
(I'm on Ember 1.12)

**Comment by aexmachina** [comment]
Yeah, the problem is with the version of node you're using. That should be
fixed now.​

**Comment by Leooo** [comment]
But I just used you last release (4.3.1)?? Shall I update node?

**Comment by aexmachina** [comment]
Update to 4.3.2.

**Comment by Leooo** [comment]
OK didn't see you just pushed 4.3.2

Compiling fine now, though (sorry..) when using `controller("authenticated")' in the console it gives an error msg:
`
Uncaught TypeError: Cannot read property 'controller' of undefined(…)prop @ ember-devtools.js:163(anonymous function) @ VM573:2InjectedScript._evaluateOn @ VM189:875InjectedScript._evaluateAndWrap @ VM189:808InjectedScript.evaluate @ VM189:664
controller("authenticated")
`

I see those lines: 
`
props.map(function (name) {
        if (skipGlobalize.indexOf(name) !== -1) return;
        var prop = _this2[name];
        if (typeof prop === 'function') {
          prop = function () {
            return this[name].apply(this, arguments);
          };
        }
        _this2.global[name] = prop;
      });
`

Should `this[name]` be `_this2[name]` maybe??

**Comment by aexmachina** [comment]
That should be fixed in the latest release.

**Comment by Leooo** [comment]
same problem with 4.4.1 version: `Uncaught TypeError: Cannot read property 'controller' of undefined` :(

I can reopen an issue if needed.

L

**Comment by aexmachina** [comment]
That sounds like an issue with how it's being called. Can you send me an example. Also are you using the `globalize` option?

**Comment by Leooo** [comment]
I use the following settings in config/environment.js:
`````
  ENV["ember-devtools"]={
    global: true,
    enabled: environment === 'development' || true
  }
`````

the exception occurs in the `globallize()` function, when calling in the console `controller("authenticated")`:

`````
      props.map(function (name) {
        if (skipGlobalize.indexOf(name) !== -1) return;
        var prop = _this2[name];
        if (typeof prop === 'function') {
          prop = function () {
            return this[name].apply(this, arguments);//exception occurs on this line
          };
        }
        _this2.global[name] = prop;
      });
`````

Not sure what you eman by "sending an example"?

**Comment by aexmachina** [comment]
Ah yes! Okay, great thanks for the bug report. That's fixed in v4.4.2 :+1:

**Comment by Leooo** [comment]
getting more and more lost. Now 
`````
cont=controller("authenticated/proximity")
cont.constructor//frontend@controller:authenticated/proximity/profile/assessment/index:
`````

**Comment by aexmachina** [comment]
Hmmn, I'm definitely not seeing that behaviour here. I can strongly suggest that that'll be caused by something at your end. Here's the full code for the `controller` function:

```js
  lookup(name) {
    return this.container.lookup(name);
  },
  controller(name) {
    name = name || this.currentRouteName();
    return this.lookup(`controller:${name}`);
  },
```

**Comment by Leooo** [comment]
yes that's because `window.currentRouteName()` returns the current route name. Don't have `currentRouteName` attached to the console anywhere in my code.

**Comment by Leooo** [comment]
`````
  //ember-devtools/services/ember-devtools.js
  currentRouteName() {
    return this.controller('application').get('currentRouteName');
  },
`````

?

**Comment by aexmachina** [comment]
That's not relevant because you're specifying the `name` parameter in the call.

**Comment by Leooo** [comment]
right. Don't have time to investigate right now, using `global:"devtools"` I have the right controller for `devtools.controller("public")`

**Comment by aexmachina** [comment]
Right, that is very strange. Is this happening in tests or while running the application? What about the example you gave above `devtools.controller("authenticated/proximity")`?

**Comment by Leooo** [comment]
It's happening in development environment, in the console. Using controller("XX") always sends the currentRouteName, except when using `global:"devtools"`. Then I did override the window / console with my own log functions so I can't be sure at this stage that this the problem is not coming from my side.

**Comment by aexmachina** [comment]
Okay I've found the issue now. Thanks for your patience! Should be fixed in the latest release when in globals mode.
